# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rcomment.proto\x12\x0eserver.comment"}\n\x11NewCommentRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x11\n\tsubreddit\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\x12\n\n\x02id\x18\x05 \x01(\t\x12\x14\n\x0csubreddit_id\x18\x06 \x01(\t" \n\x12NewCommentResponse\x12\n\n\x02id\x18\x01 \x01(\t2^\n\x07\x43omment\x12S\n\nNewComment\x12!.server.comment.NewCommentRequest\x1a".server.comment.NewCommentResponseB-Z+github.com/kwanok/minsim-api/server/commentb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "comment_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z+github.com/kwanok/minsim-api/server/comment"
    _globals["_NEWCOMMENTREQUEST"]._serialized_start = 33
    _globals["_NEWCOMMENTREQUEST"]._serialized_end = 158
    _globals["_NEWCOMMENTRESPONSE"]._serialized_start = 160
    _globals["_NEWCOMMENTRESPONSE"]._serialized_end = 192
    _globals["_COMMENT"]._serialized_start = 194
    _globals["_COMMENT"]._serialized_end = 288
# @@protoc_insertion_point(module_scope)
