# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import post_pb2 as post__pb2


class PostStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A service.Channel.
        """
        self.NewPost = channel.unary_unary(
            "/server.post.Post/NewPost",
            request_serializer=post__pb2.NewPostRequest.SerializeToString,
            response_deserializer=post__pb2.NewPostResponse.FromString,
        )


class PostServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PostServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "NewPost": grpc.unary_unary_rpc_method_handler(
            servicer.NewPost,
            request_deserializer=post__pb2.NewPostRequest.FromString,
            response_serializer=post__pb2.NewPostResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "server.post.Post", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Post(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewPost(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/server.post.Post/NewPost",
            post__pb2.NewPostRequest.SerializeToString,
            post__pb2.NewPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
